name: Docker Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: 
      - develop
      - master

jobs:

  docker_deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Check out GitHub Repo
      if: "!contains(github.event.head_commit.message, 'skip ci')"
      uses: actions/checkout@v2

    - name: Set Version and Repo Name
      run: |
        echo ::set-env name=MY_REPO_NAME::$(echo $GITHUB_REPOSITORY | awk -F / '{print $2}' | sed -e "s/:refs//")
        echo ::set-env name=APP_VERSION_NUM::$(sed -n '/module-version:/{n;p;}' kbase.yml | sed 's/ //g')
        echo ::set-env name=MY_DEV_APP::$(echo ${GITHUB_REPOSITORY}/${GITHUB_REPOSITORY}"-dev")
        # export REPO_NAME=`echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//"`
        # export APP_VERSION_NUM=`sed -n '/module-version:/{n;p;}' kbase.yml | sed 's/ //g'`
        # export MY_DEV_APP=$GITHUB_REPOSITORY/$REPO_NAME-dev

    - name: Verify Version and Repo Name
      env:
        REPO_NAME: $
      run: |
        echo $MY_REPO_NAME
        echo $APP_VERSION_NUM
        echo $MY_DEV_APP
        echo $GITHUB_REPOSITORY
        
    - name: Build and Push to Packages
      if: "!contains(github.event.head_commit.message, 'skip ci')"    
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ env.MY_DEV_APP }}
        tags: ${{ env.APP_VERSION_NUM }}
        tag_with_ref: true
        tag_with_sha: true