name: Docker Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: 
      - develop
      - master

jobs:

  docker_deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Check out GitHub repo
      if: "!contains(github.event.head_commit.message, 'skip ci')"
      uses: actions/checkout@v2

    - name: Retrieve version
      run: |
        export REPO_NAME=`echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//"`
        export APP_VERSION_NUM=`sed -n '/module-version:/{n;p;}' kbase.yml | sed 's/ //g'`

        
    - name: Build and Push to Packages
      if: "!contains(github.event.head_commit.message, 'skip ci')"    
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: jsfillman/$REPO_NAME/$REPO_NAME-dev
        tags: ${{ env.APP_VERSION_NUM }}
        tag_with_ref: true
        tag_with_sha: true