name: Tag Next

# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: 
#       - develop
#       - master

on:
  pull_request:
    types: [ labeled ]

jobs:

  docker_retag:
    runs-on: ubuntu-latest
    steps:

    - name: Check out GitHub Repo
      uses: actions/checkout@v2

    - name: Set Version and Repo Name
      run: |
        echo ::set-env name=APP_VERSION_NUM::$(sed -n '/module-version:/{n;p;}' kbase.yml | sed 's/ //g')
        echo ::set-env name=MY_DEV_APP::$(echo ${GITHUB_REPOSITORY}/$(echo $GITHUB_REPOSITORY | awk -F / '{print $2}' | sed -e "s/:refs//")"-next")
        # export REPO_NAME=`echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//"`
        # export APP_VERSION_NUM=`sed -n '/module-version:/{n;p;}' kbase.yml | sed 's/ //g'`
        # export MY_NEXT_APP=$GITHUB_REPOSITORY/$REPO_NAME-next

    - name: Verify Version and Repo Name
      if: contains( github.event.pull_request.labels.*.name, 'next')
      run: |
        echo $APP_VERSION_NUM
        echo $MY_DEV_APP
        echo $GITHUB_REPOSITORY
        
    - name: Tag Next
      if: contains( github.event.pull_request.labels.*.name, 'next')  
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ env.MY_NEX_APP }}
        tags: ${{ env.APP_VERSION_NUM }}
        tag_with_ref: true
        tag_with_sha: true