name: KBase SDK Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  sdk_tests:
    runs-on: ubuntu-latest
    steps:

    - name: Check out GitHub repo
      if: "!contains(github.event.head_commit.message, 'skip ci')"
      uses: kbaseapps/kb_sdk_actions@1
